//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalnaApoteka.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Administrator
    {
        [Required(ErrorMessage = "Morate uneti username")]
        [Display(Name = "Username:")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Morate uneti password")]
        [Display(Name = "Password:")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Morate uneti ime")]
        [Display(Name = "Ime:")]
        public string Ime { get; set; }
        [Required(ErrorMessage = "Morate uneti prezime")]
        [Display(Name = "Prezime:")]
        public string Prezime { get; set; }
        [Required(ErrorMessage = "Morate uneti pol")]
        [Display(Name = "Pol:")]
        public string Pol { get; set; }
        [Required(ErrorMessage = "Morate uneti mail")]
        [Display(Name = "Mail:")]
        public string Mail { get; set; }
        [Required(ErrorMessage = "Morate uneti telefon")]
        [Display(Name = "Telefon:")]
        public string Telefon { get; set; }
        public int Legalan { get; set; }
    }
}
