//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalnaApoteka.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DigitalnoZdravstvoEntities : DbContext
    {
        public DigitalnoZdravstvoEntities()
            : base("name=DigitalnoZdravstvoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Apotekar> Apotekars { get; set; }
        public virtual DbSet<Klinika> Klinikas { get; set; }
        public virtual DbSet<Lek> Leks { get; set; }
        public virtual DbSet<Lekar> Lekars { get; set; }
        public virtual DbSet<Pacijent> Pacijents { get; set; }
        public virtual DbSet<Recept> Recepts { get; set; }
        public virtual DbSet<Termin> Termins { get; set; }
        public virtual DbSet<Tip> Tips { get; set; }
        public virtual DbSet<Zamena> Zamenas { get; set; }
        public virtual DbSet<Apoteka> Apotekas { get; set; }
    }
}
