//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalnaApoteka.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Apotekar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apotekar()
        {
            this.Recepts = new HashSet<Recept>();
        }

        [Required(ErrorMessage = "Unesite username")]
        [Display(Name = "Username")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Unesite password")]
        [Display(Name = "Password")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Unesite ime")]
        [Display(Name = "Ime")]
        public string Ime { get; set; }
        [Required(ErrorMessage = "Unesite prezime")]
        [Display(Name = "Prezime")]
        public string Prezime { get; set; }
        [Required(ErrorMessage = "Unesite datum rodjenja")]
        [DataType(DataType.Date)]
        [Display(Name = "Datum Rodjenja")]
        public System.DateTime DatumRodjenja { get; set; }
        [Required(ErrorMessage = "Unesite mail")]
        [Display(Name = "Mail")]
        public string Mail { get; set; }
        [Required(ErrorMessage = "Unesite telefon")]
        [Display(Name = "Telefon")]
        public string Telefon { get; set; }
        [Required(ErrorMessage = "Unesite pol")]
        [Display(Name = "Pol")]
        public string Pol { get; set; }
        
        public int Legalan { get; set; }
        public int idApoteka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recept> Recepts { get; set; }
        public virtual Apoteka Apoteka { get; set; }
    }
}
