//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalnaApoteka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lek()
        {
            this.Recepts = new HashSet<Recept>();
            this.Zamenas = new HashSet<Zamena>();
            this.Zamenas1 = new HashSet<Zamena>();
        }
    
        public int idLek { get; set; }
        public string Naziv { get; set; }
        public int NaRecept { get; set; }
        public string Proizvodjac { get; set; }
        public float Cena { get; set; }
        public int idTip { get; set; }
        public int SnizenjeRecept { get; set; }
    
        public virtual Tip Tip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recept> Recepts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamena> Zamenas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zamena> Zamenas1 { get; set; }
    }
}
