//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalnaApoteka.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pacijent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacijent()
        {
            this.Recepts = new HashSet<Recept>();
            this.Termins = new HashSet<Termin>();
        }

        [Required(ErrorMessage = "Unesite username")]
        [Display(Name = "Username")]
        public string Username { get; set; }
        [Required(ErrorMessage = "Unesite password")]
        [Display(Name = "Password")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Morate uneti ime")]
        [Display(Name = "Ime:")]
        public string Ime { get; set; }
        [Required(ErrorMessage = "Morate uneti prezime")]
        [Display(Name = "Prezime:")]
        public string Prezime { get; set; }
        [Required(ErrorMessage = "Morate uneti datum rodjenja")]
        [Display(Name = "Datum Rodjenja:")]
        [DataType(DataType.Date)]
        public System.DateTime DatumRodjenja { get; set; }
        [Required(ErrorMessage = "Morate uneti mail")]
        [Display(Name = "Mail:")]
        [DataType(DataType.EmailAddress)]
        public string Mail { get; set; }
        [Required(ErrorMessage = "Morate uneti telefon")]
        [Display(Name = "Telefon:")]
        [DataType(DataType.PhoneNumber)]
        public string Telefon { get; set; }
        [Required(ErrorMessage = "Morate uneti pol")]
        [Display(Name = "Pol:")]
        public string Pol { get; set; }
        [Required(ErrorMessage = "Morate uneti JMBG")]
        [Display(Name = "JMBG:")]
        [RegularExpression(@"[0-9]{13}", ErrorMessage = "JMBG mora imati 13 cifri")]
        public string JMBG { get; set; }
        [Required(ErrorMessage = "Morate uneti BLK")]
        [Display(Name = "BLK:")]
        [RegularExpression(@"[0-9]{11}", ErrorMessage = "BZK mora imati 11 cifri")]
        public string BLK { get; set; }
        [Required(ErrorMessage = "Morate uneti BZK")]
        [Display(Name = "BZK:")]
        [RegularExpression(@"[0-9]{11}", ErrorMessage = "BZK mora imati 11 cifri")]
        public string BZK { get; set; }
        [Required(ErrorMessage = "Morate uneti LBO")]
        [Display(Name = "LBO:")]
        [RegularExpression(@"[0-9]{11}", ErrorMessage = "LBO mora imati 11 cifri")]
        public string LBO { get; set; }
        [Required(ErrorMessage = "Morate uneti da li je pacijent osiguran")]
        [Display(Name = "Osiguran:")]
        public int Osiguran { get; set; }
        [Required(ErrorMessage = "Morate uneti da li je pacijent hronicar")]
        [Display(Name = "Hronicar:")]
        public int Hronicar { get; set; }
        public int Legalan { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recept> Recepts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Termin> Termins { get; set; }
    }
}
