//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalnaApoteka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termin
    {
        public int idTermin { get; set; }
        public System.DateTime TerminPocetak { get; set; }
        public System.DateTime TerminKraj { get; set; }
        public string idPacijent { get; set; }
        public string idLekar { get; set; }
        public string Opis { get; set; }
    
        public virtual Lekar Lekar { get; set; }
        public virtual Pacijent Pacijent { get; set; }
    }
}
