//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalnaApoteka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamena
    {
        public int idZamena { get; set; }
        public int idLek1 { get; set; }
        public int idLek2 { get; set; }
    
        public virtual Lek Lek { get; set; }
        public virtual Lek Lek1 { get; set; }
    }
}
